name: கட்டிவெளியீடு
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: எடு புதியது
      uses: actions/checkout@master

    - name: கட்டு
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'Azhagi+1.zip'
        path: ./அழகி+
        exclusions: '*.git* /*node_modules/* .editorconfig'

    - name: வெளியீடு
      uses: ncipollo/release-action@v1
      with:
        artifacts: "Azhagi+1.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: அழகி+1
