name: கட்டி பதிவேற்றி வெளியிடு
on: [push]
jobs:
  கட்டு:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: கட்டி வெளியிடு
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'அழகி+.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
  வெளியீடு:
    runs-on: ubuntu-latest
    steps:
    - name: பதிவேற்றி வெளியிடு
      uses: ncipollo/release-action@v1
      with:
        artifacts: 'அழகி+.zip'
        token: ${{ secrets.GITHUB_TOKEN }}

