name: Continuous Integration
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r அழகி+.zip அழகி+
      - uses: actions/upload-artifact@v2
        with:
          name: அழகி+.zip