name: கட்டிவெளியீடு
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r அழகி+.zip அழகி+
